### ISSUE TITLE
pymol is not pip installable

### ISSUE THREAD

**Issue by arunraja-hub** [guaguabujianle/GIGN#2]
Hi, how did you install pymol to run your code? pip install pymol does not work
conda install pymol changes the version of pytorch which causes torch related issues

**Comment by guaguabujianle** [comment]
I recall that I used 'conda install -c conda-forge pymol-open-source' to install PyMOL. However, if it results in any conflicts, you have the option to create a separate environment and install PyMOL. PyMOL is solely utilized for preprocessing purposes.

**Comment by arunraja-hub** [comment]
Thank you for the very quick reply! 
Also, the _ligand.pdb files are not available under https://github.com/guaguabujianle/GIGN/tree/ef514d326202d71b0674ae20e95456454bf10c6e/GIGN/data/toy_set/1a61 as per https://github.com/guaguabujianle/GIGN/blob/ef514d326202d71b0674ae20e95456454bf10c6e/GIGN/preprocessing.py#L42C15-L42C15

Could you please check this? thanks

**Comment by arunraja-hub** [comment]
@guaguabujianle a gentle reminder, thanks

**Comment by guaguabujianle** [comment]
Ensure that Open Babel is installed using the command like ‘conda install -c conda-forge openbabel’ and verify its functionality.
In the provided source code (preprocessing.py), there's a method to convert a 'mol2' file to '_ligand.pdb'. The relevant snippet is:
if input_ligand_format != 'pdb':
    ligand_input_path = os.path.join(data_dir, cid, f'{cid}_ligand.{input_ligand_format}')
    ligand_path = ligand_input_path.replace(f".{input_ligand_format}", ".pdb")
    os.system(f'obabel {ligand_input_path} -O {ligand_path} -d')
Please ensure that Open Babel operates correctly.

**Comment by arunraja-hub** [comment]
Thank you very much!
