### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by arunraja-hub** [guaguabujianle/GIGN#3]
Is it the same exact dataset for EGNN, GIGN and IGN?

**Comment by guaguabujianle** [comment]
They have minor differences. Some data points that fail to convert into graphs are removed.

**Comment by arunraja-hub** [comment]
Since all of the above mentioned models are graph based, I am guessing the same data samples were used for each of them? 
Also for IGN, I noticed that you used DGL. Have you tried using PyTorch?

**Comment by guaguabujianle** [comment]
Yes, all the methods utilize the same data samples. The implementation of the IGN was sourced directly from the original GitHub project at "https://github.com/zjujdj/InteractionGraphNet/tree/master", as mentioned in the README.md. We did not modify the method.

**Comment by arunraja-hub** [comment]
Thanks!
