### ISSUE TITLE
question about how to use GIGN

### ISSUE THREAD

**Issue by dazuihoudaidai** [guaguabujianle/GIGN#4]
Derar author
Thanks for your perfect work.I have done the training and testing followed the instruction.After running `predict.py` ，the result is _valid_rmse-1.1538, valid_r-0.7838, test2013_rmse-1.4888, test2013_r-0.7789, test2016_rmse-1.2674, test2016_r-0.8127, test2019_rmse-1.3867, test2019_r-0.6461_  .It seems a validation of the module.But how can i **use** the trained module to predict the binding affinity of any given protein and ligand.
Thank you!

**Comment by guaguabujianle** [comment]
Hi, you can use 'preprocessing.py' to extract the pocket and convert both the pocket and ligand into a tuple, like complex = (ligand, pocket), and save it as a pickle file. The 'preprocessing.py' file already has everything you need to process a protein and pocket pair. Just make sure you have Pymol and Openbabel installed on your computer. Later, you can use 'dataset_GIGN' to convert the pickle object into a graph. Finally, you can use GIGN to predict the binding affinity.

**Comment by dazuihoudaidai** [comment]
作者您好！
    为了更清楚的说明并解决问题，我再用中文解释一下。我已经大致明白您的意思了，现在我遇到的问题是当我用toy_set来运行`preprocessing.py`时会出现一串*** Open Babel Warning  in OpenBabel::MOL2Format::ReadMolecule     Failed to kekulize aromatic bonds in MOL2 file (title is xxxx_ligand)的错误。这是否意味这提取并保存pickle文件失败？，pickle文件会保存在哪里呢？然后我再运行`dataset_GIGN`时会显示Generate Complex Graph...然后就没有反应了。如果再运行`predict.py`就会出现上文的一串数据。看起来像是评价模型的两个参数。
    我想知道正常运行的结果是怎样的。然后怎样用GIGN来预测任意蛋白和配体的结合亲和力，得到的结果会是一个结合力的数值来评价吗？
非常感谢您的解答！

**Comment by guaguabujianle** [comment]
你可以加我的QQ:418951722
