### ISSUE TITLE
Could you provide the dataset for the MGraphDTA ?

### ISSUE THREAD

**Issue by AustinApple** [guaguabujianle/GIGN#5]
Hello,
Could you provide the dataset for the MGraphDTA in the benchmark (Table 1 in the paper)? Another question is how you get the amino acid sequence from a PDB file with multiple amino acid sequences. Take 1a0q for instance, there are two amino acid sequences in the .pdb file, so which sequence did you select, or select both, and what kind of way to combine them for training MGraphDTA?

Thanks,

**Comment by guaguabujianle** [comment]
The dataset is available for download at the following link: https://drive.google.com/drive/folders/1vUS0HVneJ5f2GaZ8NLZndIuFOv-McG0G?usp=sharing. If a .pdb file contains multiple amino acid sequences, they are concatenated in the current format. There may be better methods to handle multiple sequences.

**Comment by AustinApple** [comment]
Thank you for sharing the dataset.
